// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map_renderer.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_map_5frenderer_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_map_5frenderer_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "svg.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_map_5frenderer_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_map_5frenderer_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_map_5frenderer_2eproto;
namespace map_renderer_proto {
class MapVisualizationSettings;
struct MapVisualizationSettingsDefaultTypeInternal;
extern MapVisualizationSettingsDefaultTypeInternal _MapVisualizationSettings_default_instance_;
}  // namespace map_renderer_proto
PROTOBUF_NAMESPACE_OPEN
template<> ::map_renderer_proto::MapVisualizationSettings* Arena::CreateMaybeMessage<::map_renderer_proto::MapVisualizationSettings>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace map_renderer_proto {

// ===================================================================

class MapVisualizationSettings final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:map_renderer_proto.MapVisualizationSettings) */ {
 public:
  inline MapVisualizationSettings() : MapVisualizationSettings(nullptr) {}
  ~MapVisualizationSettings() override;
  explicit PROTOBUF_CONSTEXPR MapVisualizationSettings(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MapVisualizationSettings(const MapVisualizationSettings& from);
  MapVisualizationSettings(MapVisualizationSettings&& from) noexcept
    : MapVisualizationSettings() {
    *this = ::std::move(from);
  }

  inline MapVisualizationSettings& operator=(const MapVisualizationSettings& from) {
    CopyFrom(from);
    return *this;
  }
  inline MapVisualizationSettings& operator=(MapVisualizationSettings&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MapVisualizationSettings& default_instance() {
    return *internal_default_instance();
  }
  static inline const MapVisualizationSettings* internal_default_instance() {
    return reinterpret_cast<const MapVisualizationSettings*>(
               &_MapVisualizationSettings_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MapVisualizationSettings& a, MapVisualizationSettings& b) {
    a.Swap(&b);
  }
  inline void Swap(MapVisualizationSettings* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MapVisualizationSettings* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MapVisualizationSettings* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MapVisualizationSettings>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MapVisualizationSettings& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MapVisualizationSettings& from) {
    MapVisualizationSettings::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MapVisualizationSettings* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "map_renderer_proto.MapVisualizationSettings";
  }
  protected:
  explicit MapVisualizationSettings(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kColorPaletteFieldNumber = 12,
    kBusLabelOffsetFieldNumber = 7,
    kStopLabelOffsetFieldNumber = 9,
    kUnderlayerColorFieldNumber = 10,
    kWidthFieldNumber = 1,
    kHeightFieldNumber = 2,
    kPaddingFieldNumber = 3,
    kLineWidthFieldNumber = 4,
    kStopRadiusFieldNumber = 5,
    kBusLabelFontSizeFieldNumber = 6,
    kStopLabelFontSizeFieldNumber = 8,
    kUnderlayerWidthFieldNumber = 11,
  };
  // repeated .svg_proto.Color color_palette = 12;
  int color_palette_size() const;
  private:
  int _internal_color_palette_size() const;
  public:
  void clear_color_palette();
  ::svg_proto::Color* mutable_color_palette(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::svg_proto::Color >*
      mutable_color_palette();
  private:
  const ::svg_proto::Color& _internal_color_palette(int index) const;
  ::svg_proto::Color* _internal_add_color_palette();
  public:
  const ::svg_proto::Color& color_palette(int index) const;
  ::svg_proto::Color* add_color_palette();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::svg_proto::Color >&
      color_palette() const;

  // .svg_proto.Point bus_label_offset = 7;
  bool has_bus_label_offset() const;
  private:
  bool _internal_has_bus_label_offset() const;
  public:
  void clear_bus_label_offset();
  const ::svg_proto::Point& bus_label_offset() const;
  PROTOBUF_NODISCARD ::svg_proto::Point* release_bus_label_offset();
  ::svg_proto::Point* mutable_bus_label_offset();
  void set_allocated_bus_label_offset(::svg_proto::Point* bus_label_offset);
  private:
  const ::svg_proto::Point& _internal_bus_label_offset() const;
  ::svg_proto::Point* _internal_mutable_bus_label_offset();
  public:
  void unsafe_arena_set_allocated_bus_label_offset(
      ::svg_proto::Point* bus_label_offset);
  ::svg_proto::Point* unsafe_arena_release_bus_label_offset();

  // .svg_proto.Point stop_label_offset = 9;
  bool has_stop_label_offset() const;
  private:
  bool _internal_has_stop_label_offset() const;
  public:
  void clear_stop_label_offset();
  const ::svg_proto::Point& stop_label_offset() const;
  PROTOBUF_NODISCARD ::svg_proto::Point* release_stop_label_offset();
  ::svg_proto::Point* mutable_stop_label_offset();
  void set_allocated_stop_label_offset(::svg_proto::Point* stop_label_offset);
  private:
  const ::svg_proto::Point& _internal_stop_label_offset() const;
  ::svg_proto::Point* _internal_mutable_stop_label_offset();
  public:
  void unsafe_arena_set_allocated_stop_label_offset(
      ::svg_proto::Point* stop_label_offset);
  ::svg_proto::Point* unsafe_arena_release_stop_label_offset();

  // .svg_proto.Color underlayer_color = 10;
  bool has_underlayer_color() const;
  private:
  bool _internal_has_underlayer_color() const;
  public:
  void clear_underlayer_color();
  const ::svg_proto::Color& underlayer_color() const;
  PROTOBUF_NODISCARD ::svg_proto::Color* release_underlayer_color();
  ::svg_proto::Color* mutable_underlayer_color();
  void set_allocated_underlayer_color(::svg_proto::Color* underlayer_color);
  private:
  const ::svg_proto::Color& _internal_underlayer_color() const;
  ::svg_proto::Color* _internal_mutable_underlayer_color();
  public:
  void unsafe_arena_set_allocated_underlayer_color(
      ::svg_proto::Color* underlayer_color);
  ::svg_proto::Color* unsafe_arena_release_underlayer_color();

  // double width = 1;
  void clear_width();
  double width() const;
  void set_width(double value);
  private:
  double _internal_width() const;
  void _internal_set_width(double value);
  public:

  // double height = 2;
  void clear_height();
  double height() const;
  void set_height(double value);
  private:
  double _internal_height() const;
  void _internal_set_height(double value);
  public:

  // double padding = 3;
  void clear_padding();
  double padding() const;
  void set_padding(double value);
  private:
  double _internal_padding() const;
  void _internal_set_padding(double value);
  public:

  // double line_width = 4;
  void clear_line_width();
  double line_width() const;
  void set_line_width(double value);
  private:
  double _internal_line_width() const;
  void _internal_set_line_width(double value);
  public:

  // double stop_radius = 5;
  void clear_stop_radius();
  double stop_radius() const;
  void set_stop_radius(double value);
  private:
  double _internal_stop_radius() const;
  void _internal_set_stop_radius(double value);
  public:

  // int32 bus_label_font_size = 6;
  void clear_bus_label_font_size();
  int32_t bus_label_font_size() const;
  void set_bus_label_font_size(int32_t value);
  private:
  int32_t _internal_bus_label_font_size() const;
  void _internal_set_bus_label_font_size(int32_t value);
  public:

  // int32 stop_label_font_size = 8;
  void clear_stop_label_font_size();
  int32_t stop_label_font_size() const;
  void set_stop_label_font_size(int32_t value);
  private:
  int32_t _internal_stop_label_font_size() const;
  void _internal_set_stop_label_font_size(int32_t value);
  public:

  // double underlayer_width = 11;
  void clear_underlayer_width();
  double underlayer_width() const;
  void set_underlayer_width(double value);
  private:
  double _internal_underlayer_width() const;
  void _internal_set_underlayer_width(double value);
  public:

  // @@protoc_insertion_point(class_scope:map_renderer_proto.MapVisualizationSettings)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::svg_proto::Color > color_palette_;
    ::svg_proto::Point* bus_label_offset_;
    ::svg_proto::Point* stop_label_offset_;
    ::svg_proto::Color* underlayer_color_;
    double width_;
    double height_;
    double padding_;
    double line_width_;
    double stop_radius_;
    int32_t bus_label_font_size_;
    int32_t stop_label_font_size_;
    double underlayer_width_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_map_5frenderer_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MapVisualizationSettings

// double width = 1;
inline void MapVisualizationSettings::clear_width() {
  _impl_.width_ = 0;
}
inline double MapVisualizationSettings::_internal_width() const {
  return _impl_.width_;
}
inline double MapVisualizationSettings::width() const {
  // @@protoc_insertion_point(field_get:map_renderer_proto.MapVisualizationSettings.width)
  return _internal_width();
}
inline void MapVisualizationSettings::_internal_set_width(double value) {
  
  _impl_.width_ = value;
}
inline void MapVisualizationSettings::set_width(double value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:map_renderer_proto.MapVisualizationSettings.width)
}

// double height = 2;
inline void MapVisualizationSettings::clear_height() {
  _impl_.height_ = 0;
}
inline double MapVisualizationSettings::_internal_height() const {
  return _impl_.height_;
}
inline double MapVisualizationSettings::height() const {
  // @@protoc_insertion_point(field_get:map_renderer_proto.MapVisualizationSettings.height)
  return _internal_height();
}
inline void MapVisualizationSettings::_internal_set_height(double value) {
  
  _impl_.height_ = value;
}
inline void MapVisualizationSettings::set_height(double value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:map_renderer_proto.MapVisualizationSettings.height)
}

// double padding = 3;
inline void MapVisualizationSettings::clear_padding() {
  _impl_.padding_ = 0;
}
inline double MapVisualizationSettings::_internal_padding() const {
  return _impl_.padding_;
}
inline double MapVisualizationSettings::padding() const {
  // @@protoc_insertion_point(field_get:map_renderer_proto.MapVisualizationSettings.padding)
  return _internal_padding();
}
inline void MapVisualizationSettings::_internal_set_padding(double value) {
  
  _impl_.padding_ = value;
}
inline void MapVisualizationSettings::set_padding(double value) {
  _internal_set_padding(value);
  // @@protoc_insertion_point(field_set:map_renderer_proto.MapVisualizationSettings.padding)
}

// double line_width = 4;
inline void MapVisualizationSettings::clear_line_width() {
  _impl_.line_width_ = 0;
}
inline double MapVisualizationSettings::_internal_line_width() const {
  return _impl_.line_width_;
}
inline double MapVisualizationSettings::line_width() const {
  // @@protoc_insertion_point(field_get:map_renderer_proto.MapVisualizationSettings.line_width)
  return _internal_line_width();
}
inline void MapVisualizationSettings::_internal_set_line_width(double value) {
  
  _impl_.line_width_ = value;
}
inline void MapVisualizationSettings::set_line_width(double value) {
  _internal_set_line_width(value);
  // @@protoc_insertion_point(field_set:map_renderer_proto.MapVisualizationSettings.line_width)
}

// double stop_radius = 5;
inline void MapVisualizationSettings::clear_stop_radius() {
  _impl_.stop_radius_ = 0;
}
inline double MapVisualizationSettings::_internal_stop_radius() const {
  return _impl_.stop_radius_;
}
inline double MapVisualizationSettings::stop_radius() const {
  // @@protoc_insertion_point(field_get:map_renderer_proto.MapVisualizationSettings.stop_radius)
  return _internal_stop_radius();
}
inline void MapVisualizationSettings::_internal_set_stop_radius(double value) {
  
  _impl_.stop_radius_ = value;
}
inline void MapVisualizationSettings::set_stop_radius(double value) {
  _internal_set_stop_radius(value);
  // @@protoc_insertion_point(field_set:map_renderer_proto.MapVisualizationSettings.stop_radius)
}

// int32 bus_label_font_size = 6;
inline void MapVisualizationSettings::clear_bus_label_font_size() {
  _impl_.bus_label_font_size_ = 0;
}
inline int32_t MapVisualizationSettings::_internal_bus_label_font_size() const {
  return _impl_.bus_label_font_size_;
}
inline int32_t MapVisualizationSettings::bus_label_font_size() const {
  // @@protoc_insertion_point(field_get:map_renderer_proto.MapVisualizationSettings.bus_label_font_size)
  return _internal_bus_label_font_size();
}
inline void MapVisualizationSettings::_internal_set_bus_label_font_size(int32_t value) {
  
  _impl_.bus_label_font_size_ = value;
}
inline void MapVisualizationSettings::set_bus_label_font_size(int32_t value) {
  _internal_set_bus_label_font_size(value);
  // @@protoc_insertion_point(field_set:map_renderer_proto.MapVisualizationSettings.bus_label_font_size)
}

// .svg_proto.Point bus_label_offset = 7;
inline bool MapVisualizationSettings::_internal_has_bus_label_offset() const {
  return this != internal_default_instance() && _impl_.bus_label_offset_ != nullptr;
}
inline bool MapVisualizationSettings::has_bus_label_offset() const {
  return _internal_has_bus_label_offset();
}
inline const ::svg_proto::Point& MapVisualizationSettings::_internal_bus_label_offset() const {
  const ::svg_proto::Point* p = _impl_.bus_label_offset_;
  return p != nullptr ? *p : reinterpret_cast<const ::svg_proto::Point&>(
      ::svg_proto::_Point_default_instance_);
}
inline const ::svg_proto::Point& MapVisualizationSettings::bus_label_offset() const {
  // @@protoc_insertion_point(field_get:map_renderer_proto.MapVisualizationSettings.bus_label_offset)
  return _internal_bus_label_offset();
}
inline void MapVisualizationSettings::unsafe_arena_set_allocated_bus_label_offset(
    ::svg_proto::Point* bus_label_offset) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.bus_label_offset_);
  }
  _impl_.bus_label_offset_ = bus_label_offset;
  if (bus_label_offset) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:map_renderer_proto.MapVisualizationSettings.bus_label_offset)
}
inline ::svg_proto::Point* MapVisualizationSettings::release_bus_label_offset() {
  
  ::svg_proto::Point* temp = _impl_.bus_label_offset_;
  _impl_.bus_label_offset_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::svg_proto::Point* MapVisualizationSettings::unsafe_arena_release_bus_label_offset() {
  // @@protoc_insertion_point(field_release:map_renderer_proto.MapVisualizationSettings.bus_label_offset)
  
  ::svg_proto::Point* temp = _impl_.bus_label_offset_;
  _impl_.bus_label_offset_ = nullptr;
  return temp;
}
inline ::svg_proto::Point* MapVisualizationSettings::_internal_mutable_bus_label_offset() {
  
  if (_impl_.bus_label_offset_ == nullptr) {
    auto* p = CreateMaybeMessage<::svg_proto::Point>(GetArenaForAllocation());
    _impl_.bus_label_offset_ = p;
  }
  return _impl_.bus_label_offset_;
}
inline ::svg_proto::Point* MapVisualizationSettings::mutable_bus_label_offset() {
  ::svg_proto::Point* _msg = _internal_mutable_bus_label_offset();
  // @@protoc_insertion_point(field_mutable:map_renderer_proto.MapVisualizationSettings.bus_label_offset)
  return _msg;
}
inline void MapVisualizationSettings::set_allocated_bus_label_offset(::svg_proto::Point* bus_label_offset) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.bus_label_offset_);
  }
  if (bus_label_offset) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(bus_label_offset));
    if (message_arena != submessage_arena) {
      bus_label_offset = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, bus_label_offset, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.bus_label_offset_ = bus_label_offset;
  // @@protoc_insertion_point(field_set_allocated:map_renderer_proto.MapVisualizationSettings.bus_label_offset)
}

// int32 stop_label_font_size = 8;
inline void MapVisualizationSettings::clear_stop_label_font_size() {
  _impl_.stop_label_font_size_ = 0;
}
inline int32_t MapVisualizationSettings::_internal_stop_label_font_size() const {
  return _impl_.stop_label_font_size_;
}
inline int32_t MapVisualizationSettings::stop_label_font_size() const {
  // @@protoc_insertion_point(field_get:map_renderer_proto.MapVisualizationSettings.stop_label_font_size)
  return _internal_stop_label_font_size();
}
inline void MapVisualizationSettings::_internal_set_stop_label_font_size(int32_t value) {
  
  _impl_.stop_label_font_size_ = value;
}
inline void MapVisualizationSettings::set_stop_label_font_size(int32_t value) {
  _internal_set_stop_label_font_size(value);
  // @@protoc_insertion_point(field_set:map_renderer_proto.MapVisualizationSettings.stop_label_font_size)
}

// .svg_proto.Point stop_label_offset = 9;
inline bool MapVisualizationSettings::_internal_has_stop_label_offset() const {
  return this != internal_default_instance() && _impl_.stop_label_offset_ != nullptr;
}
inline bool MapVisualizationSettings::has_stop_label_offset() const {
  return _internal_has_stop_label_offset();
}
inline const ::svg_proto::Point& MapVisualizationSettings::_internal_stop_label_offset() const {
  const ::svg_proto::Point* p = _impl_.stop_label_offset_;
  return p != nullptr ? *p : reinterpret_cast<const ::svg_proto::Point&>(
      ::svg_proto::_Point_default_instance_);
}
inline const ::svg_proto::Point& MapVisualizationSettings::stop_label_offset() const {
  // @@protoc_insertion_point(field_get:map_renderer_proto.MapVisualizationSettings.stop_label_offset)
  return _internal_stop_label_offset();
}
inline void MapVisualizationSettings::unsafe_arena_set_allocated_stop_label_offset(
    ::svg_proto::Point* stop_label_offset) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.stop_label_offset_);
  }
  _impl_.stop_label_offset_ = stop_label_offset;
  if (stop_label_offset) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:map_renderer_proto.MapVisualizationSettings.stop_label_offset)
}
inline ::svg_proto::Point* MapVisualizationSettings::release_stop_label_offset() {
  
  ::svg_proto::Point* temp = _impl_.stop_label_offset_;
  _impl_.stop_label_offset_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::svg_proto::Point* MapVisualizationSettings::unsafe_arena_release_stop_label_offset() {
  // @@protoc_insertion_point(field_release:map_renderer_proto.MapVisualizationSettings.stop_label_offset)
  
  ::svg_proto::Point* temp = _impl_.stop_label_offset_;
  _impl_.stop_label_offset_ = nullptr;
  return temp;
}
inline ::svg_proto::Point* MapVisualizationSettings::_internal_mutable_stop_label_offset() {
  
  if (_impl_.stop_label_offset_ == nullptr) {
    auto* p = CreateMaybeMessage<::svg_proto::Point>(GetArenaForAllocation());
    _impl_.stop_label_offset_ = p;
  }
  return _impl_.stop_label_offset_;
}
inline ::svg_proto::Point* MapVisualizationSettings::mutable_stop_label_offset() {
  ::svg_proto::Point* _msg = _internal_mutable_stop_label_offset();
  // @@protoc_insertion_point(field_mutable:map_renderer_proto.MapVisualizationSettings.stop_label_offset)
  return _msg;
}
inline void MapVisualizationSettings::set_allocated_stop_label_offset(::svg_proto::Point* stop_label_offset) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.stop_label_offset_);
  }
  if (stop_label_offset) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stop_label_offset));
    if (message_arena != submessage_arena) {
      stop_label_offset = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stop_label_offset, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.stop_label_offset_ = stop_label_offset;
  // @@protoc_insertion_point(field_set_allocated:map_renderer_proto.MapVisualizationSettings.stop_label_offset)
}

// .svg_proto.Color underlayer_color = 10;
inline bool MapVisualizationSettings::_internal_has_underlayer_color() const {
  return this != internal_default_instance() && _impl_.underlayer_color_ != nullptr;
}
inline bool MapVisualizationSettings::has_underlayer_color() const {
  return _internal_has_underlayer_color();
}
inline const ::svg_proto::Color& MapVisualizationSettings::_internal_underlayer_color() const {
  const ::svg_proto::Color* p = _impl_.underlayer_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::svg_proto::Color&>(
      ::svg_proto::_Color_default_instance_);
}
inline const ::svg_proto::Color& MapVisualizationSettings::underlayer_color() const {
  // @@protoc_insertion_point(field_get:map_renderer_proto.MapVisualizationSettings.underlayer_color)
  return _internal_underlayer_color();
}
inline void MapVisualizationSettings::unsafe_arena_set_allocated_underlayer_color(
    ::svg_proto::Color* underlayer_color) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.underlayer_color_);
  }
  _impl_.underlayer_color_ = underlayer_color;
  if (underlayer_color) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:map_renderer_proto.MapVisualizationSettings.underlayer_color)
}
inline ::svg_proto::Color* MapVisualizationSettings::release_underlayer_color() {
  
  ::svg_proto::Color* temp = _impl_.underlayer_color_;
  _impl_.underlayer_color_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::svg_proto::Color* MapVisualizationSettings::unsafe_arena_release_underlayer_color() {
  // @@protoc_insertion_point(field_release:map_renderer_proto.MapVisualizationSettings.underlayer_color)
  
  ::svg_proto::Color* temp = _impl_.underlayer_color_;
  _impl_.underlayer_color_ = nullptr;
  return temp;
}
inline ::svg_proto::Color* MapVisualizationSettings::_internal_mutable_underlayer_color() {
  
  if (_impl_.underlayer_color_ == nullptr) {
    auto* p = CreateMaybeMessage<::svg_proto::Color>(GetArenaForAllocation());
    _impl_.underlayer_color_ = p;
  }
  return _impl_.underlayer_color_;
}
inline ::svg_proto::Color* MapVisualizationSettings::mutable_underlayer_color() {
  ::svg_proto::Color* _msg = _internal_mutable_underlayer_color();
  // @@protoc_insertion_point(field_mutable:map_renderer_proto.MapVisualizationSettings.underlayer_color)
  return _msg;
}
inline void MapVisualizationSettings::set_allocated_underlayer_color(::svg_proto::Color* underlayer_color) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.underlayer_color_);
  }
  if (underlayer_color) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(underlayer_color));
    if (message_arena != submessage_arena) {
      underlayer_color = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, underlayer_color, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.underlayer_color_ = underlayer_color;
  // @@protoc_insertion_point(field_set_allocated:map_renderer_proto.MapVisualizationSettings.underlayer_color)
}

// double underlayer_width = 11;
inline void MapVisualizationSettings::clear_underlayer_width() {
  _impl_.underlayer_width_ = 0;
}
inline double MapVisualizationSettings::_internal_underlayer_width() const {
  return _impl_.underlayer_width_;
}
inline double MapVisualizationSettings::underlayer_width() const {
  // @@protoc_insertion_point(field_get:map_renderer_proto.MapVisualizationSettings.underlayer_width)
  return _internal_underlayer_width();
}
inline void MapVisualizationSettings::_internal_set_underlayer_width(double value) {
  
  _impl_.underlayer_width_ = value;
}
inline void MapVisualizationSettings::set_underlayer_width(double value) {
  _internal_set_underlayer_width(value);
  // @@protoc_insertion_point(field_set:map_renderer_proto.MapVisualizationSettings.underlayer_width)
}

// repeated .svg_proto.Color color_palette = 12;
inline int MapVisualizationSettings::_internal_color_palette_size() const {
  return _impl_.color_palette_.size();
}
inline int MapVisualizationSettings::color_palette_size() const {
  return _internal_color_palette_size();
}
inline ::svg_proto::Color* MapVisualizationSettings::mutable_color_palette(int index) {
  // @@protoc_insertion_point(field_mutable:map_renderer_proto.MapVisualizationSettings.color_palette)
  return _impl_.color_palette_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::svg_proto::Color >*
MapVisualizationSettings::mutable_color_palette() {
  // @@protoc_insertion_point(field_mutable_list:map_renderer_proto.MapVisualizationSettings.color_palette)
  return &_impl_.color_palette_;
}
inline const ::svg_proto::Color& MapVisualizationSettings::_internal_color_palette(int index) const {
  return _impl_.color_palette_.Get(index);
}
inline const ::svg_proto::Color& MapVisualizationSettings::color_palette(int index) const {
  // @@protoc_insertion_point(field_get:map_renderer_proto.MapVisualizationSettings.color_palette)
  return _internal_color_palette(index);
}
inline ::svg_proto::Color* MapVisualizationSettings::_internal_add_color_palette() {
  return _impl_.color_palette_.Add();
}
inline ::svg_proto::Color* MapVisualizationSettings::add_color_palette() {
  ::svg_proto::Color* _add = _internal_add_color_palette();
  // @@protoc_insertion_point(field_add:map_renderer_proto.MapVisualizationSettings.color_palette)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::svg_proto::Color >&
MapVisualizationSettings::color_palette() const {
  // @@protoc_insertion_point(field_list:map_renderer_proto.MapVisualizationSettings.color_palette)
  return _impl_.color_palette_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace map_renderer_proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_map_5frenderer_2eproto
